# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soft_thresh <- function(x, alpha) {
    .Call(`_SparseICA_soft_thresh`, x, alpha)
}

procrustes <- function(X, V) {
    .Call(`_SparseICA_procrustes`, X, V)
}

relax_laplace <- function(xData, newV, nu, lambda, maxit, eps = 0.000001) {
    .Call(`_SparseICA_relax_laplace`, xData, newV, nu, lambda, maxit, eps)
}

runs_relax_laplace <- function(xData, W, runs, r, nu, lambda, maxit, eps = 0.000001) {
    .Call(`_SparseICA_runs_relax_laplace`, xData, W, runs, r, nu, lambda, maxit, eps)
}

